{
 "title": "Dashboard-v1",
 "tags": [
  "ml",
  "airflow",
  "prometheus",
  "system"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Train Accuracy (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(train_accuracy_percent{job=\"pushgateway\"})"
    }
   ]
  },
  {
   "title": "Validation Accuracy (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(val_accuracy_percent{job=\"pushgateway\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Test Accuracy (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(__name__) (test_accuracy_percent{job=\"pushgateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Batch Size ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max by(__name__) (batch_size)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Epochs Trained on",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max by(__name__) (epochs)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Learning Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(__name__) (learning_rate)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "F1 Score",
   "type": "stat",
   "description": "F1=2×(Precision×Recall)/)Precision+Recall)​",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(f1_score)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Recall",
   "type": "stat",
   "description": "Recall=TP/(TP+FN)",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(recall)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Precision",
   "type": "stat",
   "description": "Precision=TP/(TP+FP)",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(precision)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Train Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(train_loss{job=\"pushgateway\"})"
    }
   ]
  },
  {
   "title": "Test Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(test_loss{job=\"pushgateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validation Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(val_loss{job=\"pushgateway\"})"
    }
   ]
  },
  {
   "title": "Memory Usage (Resident Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Gpu Utilization (%)",
   "type": "stat",
   "description": "Max Gpu utilization Reached on Last Run",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(gpu_utilization_percent)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gpu Temp ",
   "type": "stat",
   "description": "Max Gpu Temp that have reaches on last run",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(gpu_temperature_celsius)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gpu Mem",
   "type": "stat",
   "description": "Max Gpu memory used on last training run",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(gpu_memory_used_mb)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Training Accuracy over all epochs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "train_accuracy_percent", "legendFormat": "Train Accuracy" }
   ]
  },
  {
   "title": "Validation Accuracy over all epochs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "val_accuracy_percent{job=\"pushgateway\"} \r\n",
     "legendFormat": "Validation Accuracy"
    }
   ]
  },
  {
   "title": "CPU Usage (rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])"
    }
   ]
  },
  {
   "title": "Training Loss vs Validation Loss over all Epochs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "train_loss", "legendFormat": "Train Loss" },
    { "expr": "val_loss", "legendFormat": "Validation Loss" }
   ]
  },
  {
   "title": "Network I/O (Bytes per sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(process_network_receive_bytes_total[1m])",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(process_network_transmit_bytes_total[1m])",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "Go Heap Memory (In Use)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "go_memstats_heap_inuse_bytes" }
   ]
  },
  {
   "title": "Goroutines Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "targets": [
    { "expr": "go_threads" }
   ]
  },
  {
   "title": "GC Average Duration (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum[5m]) / rate(go_gc_duration_seconds_count[5m])",
     "legendFormat": "GC Duration"
    }
   ]
  }
 ]
}